package com.example.finalproject.model.enums;

public enum OrderStatus {
    PENDING_FOR_TECHNICIAN_SUGGESTION,
    PENDING_FOR_SELECTING_TECHNICIAN,
    PENDING_FOR_COMING_TO_PLACE,
    STARTED_THE_PROCESS,
    FINISHED_THE_PROCESS,
    PENDING_FOR_CHECKOUT;

}
